name : slave
hosts: all
remote_user: ubuntu
become: yes
tasks:
  - name: update
    apt:
      update_cache: yes

  - name: create directory
    file:
      path: /home/ubuntu/jenkins_home
      state: directory
      mode: '0777'

  - name: install jave
    apt:
      name: openjdk-8-jdk
    
